version: '2'
services:
  frontend:
    volumes:
      - ./frontend/src:/app/frontend/src
      - ./frontend/www:/app/frontend/www
      - ./frontend/package.json:/app/frontend/package.json
      - ./frontend/apps.config.js:/app/frontend/apps.config.js
      - ./frontend/toolbox-variables.js:/app/frontend/toolbox-variables.js
      - ./frontend/yarn.lock:/app/frontend/yarn.lock
      - ./frontend/template.ejs:/app/frontend/template.ejs
      - ./shared/src:/app/frontend/node_modules/shared/src
      - ../templatestack/template-ui/lib:/app/frontend/node_modules/template-ui/lib
      - ../templatestack/template-tools/src:/app/frontend/node_modules/template-tools/src
  api:
    volumes:
      - ./api/src:/app/api/src
      - ./api/test:/app/api/test
      - ./api/migrations:/app/api/migrations
      - ./api/package.json:/app/api/package.json
      - ./api/yarn.lock:/app/api/yarn.lock
      - ./shared/src:/app/api/node_modules/shared/src
      - ../templatestack/template-api/src:/app/api/node_modules/template-api/src
      - ../templatestack/template-tools/src:/app/api/node_modules/template-tools/src
